/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*\title Multicore LED control
 * \abstract One LED is controlled by using three different cores.
 * \description Core 0 is switching on an LED. When the LED flag is set, Core 1 is switching off the LED.
 *              Core 2 is controlling the state of the LED flag.
 *
 * \name Multicore_1_KIT_TC397_TFT
 * \version V2.0.0
 * \board APPLICATION KIT TC3X7 V2.0, KIT_A2G_TC397_5V_TFT, TC39xXX_B-Step
 * \keywords multicore, LED, AURIX, Multicore_1
 * \documents README.MD
 * \documents https://www.infineon.com/aurix-expert-training/TC39B_iLLD_UM_1_0_1_17_0.chm
 * \lastUpdated 2024-04-04
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Multicore.h"
#include "perf_workload.h"

static inline __attribute__((always_inline)) uint32 perf_inline_xorshift(uint32 val)
{
    val ^= val << 13;
    val ^= val >> 17;
    val ^= val << 5;
    return val;
}

static inline __attribute__((always_inline)) uint32 perf_inline_hash_mix(uint32 a, uint32 b)
{
    a -= b; a ^= (b << 6);
    b -= a; b ^= (a >> 8);
    a -= b; a ^= (b << 16);
    return a ^ b;
}

static inline __attribute__((always_inline)) uint32 perf_inline_rotate_acc(uint32 val, uint32 rounds)
{
    uint32 i;
    for (i = 0; i < rounds; i++)
    {
        val = (val << 7) | (val >> 25);
        val *= 0x9E3779B9u;
    }
    return val;
}

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

void _init(void)
{
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Initialize the LED and a time constant before the CPUs synchronization */
    initLEDAndTime();

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    volatile uint32 perf_marker = 0;
    while (1)
    {
        perf_run_all_workloads();
        perf_marker = perf_inline_xorshift((uint32)perf_marker + 1u);
        perf_marker = perf_inline_hash_mix((uint32)perf_marker, 0xDEADBEEFu);
        perf_marker = perf_inline_rotate_acc((uint32)perf_marker, 10u);
        turnLEDon();
    }
}
