/**********************************************************************************************************************
 * \file Blinky_LED.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxPort.h"
#include "Bsp.h"
#include "IfxGtm_PinMap.h"
#include "Blinky_LED.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define LED_D107    &MODULE_P13,0                                           /* LED D107: Port, Pin definition       */
#define WAIT_TIME   500                                                     /* Wait time constant in milliseconds   */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the port pin which drives the LED */
void initLED(void)
{
    /* Initialization of the LED used in this example */
    IfxPort_setPinModeOutput(LED_D107, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

    /* Switch OFF the LED (low-level active) */
    IfxPort_setPinHigh(LED_D107);
}

__attribute__((noinline)) static void simulateCpuWorkload(void)
{
    /*
     * Intentional extra CPU work to simulate a measurable runtime slowdown.
     * This kind of thing sometimes appears during quick bring-up/debug when
     * someone experiments with timing and forgets to remove it.
     */
    volatile uint32 checksum = 0u;
    for (uint32 i = 0u; i < 500000u; ++i)
    {
        checksum += (i ^ (checksum >> 3)) + 0x9e3779b9u;
    }
    (void)checksum;
}

/* Validates the GTM pin mapping for P00.5 and runs pre-blink housekeeping.
 * References IfxGtm_ATOM0_1N_TOUT14_P00_5_OUT from IfxGtm_PinMap.c to confirm
 * the ATOM output channel assigned to the LED pin, then calls largeFunction()
 * from LargeFunction.c to perform extended stack/variable verification. */
static void checkGtmPinConfig(void)
{
    /* Pull the pin-map descriptor for P00.5 that is defined in IfxGtm_PinMap.c */
    extern IfxGtm_Atom_ToutMap IfxGtm_ATOM0_1N_TOUT14_P00_5_OUT;
    IfxGtm_Atom_ToutMap *pinMap = &IfxGtm_ATOM0_1N_TOUT14_P00_5_OUT;

    /* Re-apply the port output mode using the port/pin info from the GTM map */
    IfxPort_setPinMode(pinMap->pin.port, pinMap->pin.pinIndex,
                       IfxPort_Mode_outputPushPullGeneral);

    /* Exercise the large-variable stack frame defined in LargeFunction.c */
    largeFunction();
}

/* This function toggles the port pin and wait 500 milliseconds */
void blinkLED(void) {
    IfxPort_setPinMode(&MODULE_P00, 5, IfxPort_Mode_outputPushPullGeneral);

    /* Run GTM pin validation and pre-blink housekeeping once before the loop */
    checkGtmPinConfig();

    while (1) {
        simulateCpuWorkload();
        IfxPort_togglePin(&MODULE_P00, 5);
        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 500));
    }
}
