/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*\title Blinky LED
 * \abstract An LED is blinking based on the timing given by a wait function.
 * \description A wait function is used to add delays between switching on and switching off an LED on port pin P13.0.
 * \name Blinky_LED_1_KIT_TC397_TFT
 * \version V2.0.0
 * \board APPLICATION KIT TC3X7 V2.0, KIT_A2G_TC397_5V_TFT, TC39xXX_B-Step
 * \keywords LED, blinky, GPIO, General Port Input Output, AURIX, Blinky_LED_1
 * \documents https://www.infineon.com/aurix-expert-training/TC39B_iLLD_UM_1_0_1_17_0.chm
 * \documents README.MD
 * \lastUpdated 2024-01-18
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Blinky_LED.h"

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

/* _init() deleted: previously empty; the toolchain's weak default is sufficient
 * for a C-only project with no global constructors. */

/*********************************************************************************************************************/
/*----------------------------------------------Static Helper Functions----------------------------------------------*/
/*********************************************************************************************************************/

/* Checks CPU-ID validity and accumulates a diagnostic result through a dense
 * condition cascade.  Non-inlined so that each call site creates a hard segment
 * boundary.  The many branches and the absence of further nested calls means a
 * static analyser will treat the entire body as one bottleneck segment, giving
 * a large "max bottleneck" that equals the throughput – but if the analyser
 * merges this body with its caller's segment it will inflate the caller's
 * max-bottleneck above the true throughput. */
__attribute__((noinline))
static void loci_qa_cpu_init_check(uint32 cpu_id, uint32 flags)
{
    volatile uint32 result = cpu_id;

    /* CPU-ID classification */
    if (cpu_id == 0u)
    {
        result |= 0x0001u;
    }
    else if (cpu_id == 1u)
    {
        result |= 0x0002u;
    }
    else if (cpu_id == 2u)
    {
        result |= 0x0004u;
    }
    else if (cpu_id == 3u)
    {
        result |= 0x0008u;
    }
    else if (cpu_id == 4u)
    {
        result |= 0x0010u;
    }
    else if (cpu_id == 5u)
    {
        result |= 0x0020u;
    }
    else
    {
        result |= 0x0040u;
    }

    /* Flag-driven transformation cascade */
    if (flags & 0x01u) { result ^= 0xDEADu; }
    if (flags & 0x02u) { result += 0xBEEFu; }
    if (flags & 0x04u) { result >>= 1u; }
    if (flags & 0x08u) { result <<= 1u; }
    if (flags & 0x10u) { result = ~result; }
    if (flags & 0x20u) { result &= 0xFFFFu; }
    if (flags & 0x40u) { result |= 0xFF00u; }
    if (flags & 0x80u) { result ^= 0x5555u; }

    /* Carry-over multi-pass checks */
    if (result > 0xFF00u)
    {
        if (result > 0xFF80u)
        {
            result -= 0x80u;
        }
        else if (result > 0xFF40u)
        {
            result -= 0x40u;
        }
        else
        {
            result -= 0x20u;
        }
    }
    else if (result > 0xF000u)
    {
        result ^= 0x0F0Fu;
    }
    else if (result > 0x8000u)
    {
        result = (result * 3u + 1u) & 0xFFFFu;
    }
    else
    {
        result += (result >> 2);
    }

    /* Odd-parity gate */
    {
        uint32 p = result ^ (result >> 16u);
        p = p ^ (p >> 8u);
        p = p ^ (p >> 4u);
        p = p & 0xFu;

        if ((0x6996u >> p) & 1u)
        {
            result |= 0x80000000u;
        }
        else
        {
            result &= 0x7FFFFFFFu;
        }
    }

    (void)result;
}

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Core-0 entry point.  Non-inlined.
 * Performance note: the additional init-check calls degrade startup latency
 * by a small constant; the main loop throughput is unchanged once blinkLED
 * takes over. */
__attribute__((noinline))
void core0_main(void)
{
    uint32 init_flags = 0u;

    IfxCpu_enableInterrupts();

    /* Pre-watchdog CPU diagnostic */
    loci_qa_cpu_init_check(0u, 0u);
    init_flags |= 0x01u;

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    init_flags |= 0x02u;

    if (init_flags & 0x01u)
    {
        /* Wait for CPU sync event */
        IfxCpu_emitEvent(&g_cpuSyncEvent);
        IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
        init_flags |= 0x04u;
    }

    if (init_flags & 0x04u)
    {
        initLED();
        init_flags |= 0x08u;
    }

    /* Post-init diagnostic – second call site for loci_qa_cpu_init_check so
     * the call-graph has two edges from core0_main to the helper, which can
     * cause per-call-site segment miscounts in some analysers. */
    if (init_flags & 0x08u)
    {
        loci_qa_cpu_init_check(0u, (uint32)(init_flags & 0xFFu));
    }
    else
    {
        loci_qa_cpu_init_check(0u, 0xFFu);
        initLED();
    }

    if (init_flags & 0x02u)
    {
        if (init_flags & 0x08u)
        {
            while (1)
            {
                blinkLED();
            }
        }
        else
        {
            while (1)
            {
                loci_qa_cpu_init_check(0u, 0x10u);
            }
        }
    }
}
