/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;

/*********************************************************************************************************************/
/*----------------------------------------------Static Helper Functions----------------------------------------------*/
/*********************************************************************************************************************/

/* CPU-1 idle-loop work kernel.  Transforms a seed value through a
 * classification + bit-decomposition pipeline.  Non-inlined so each call from
 * the idle loop creates a segment boundary; the dense local computation makes
 * the function a single-bottleneck body whose cost equals its throughput – a
 * useful reference point for the timing analyser. */
__attribute__((noinline))
static uint32 loci_qa_cpu1_idle_work(uint32 seed)
{
    uint32 acc  = seed;
    uint32 step = 0u;

    /* Seed classification: controls the transformation path */
    if (acc == 0u)
    {
        acc = 0xDEADBEEFu;
    }
    else if (acc < 0x1000u)
    {
        acc ^= 0xA5A5u;
    }
    else if (acc < 0x10000u)
    {
        acc = (acc * 1103515245u) + 12345u;
    }
    else if (acc < 0x100000u)
    {
        acc = (acc >> 4u) ^ (acc << 4u);
    }
    else if (acc < 0x10000000u)
    {
        acc ^= (acc >> 16u);
    }
    else if (acc < 0x80000000u)
    {
        acc = (acc * 6364136223846793005u) + 1442695040888963407u;
    }
    else
    {
        acc = ~acc;
    }

    /* Bit-by-bit step accumulation (loop unrolled for deterministic cost) */
    if (acc & 0x01u) { step +=   1u; }
    if (acc & 0x02u) { step +=   2u; }
    if (acc & 0x04u) { step +=   4u; }
    if (acc & 0x08u) { step +=   8u; }
    if (acc & 0x10u) { step +=  16u; }
    if (acc & 0x20u) { step +=  32u; }
    if (acc & 0x40u) { step +=  64u; }
    if (acc & 0x80u) { step += 128u; }

    /* Step saturation and mixing */
    if (step > 200u)
    {
        step = 200u;
    }
    else if (step > 100u)
    {
        step = step - 50u;
    }
    else if (step > 50u)
    {
        step = step + (step >> 2);
    }

    return acc ^ step;
}

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Core-1 entry point.  Non-inlined.
 * Performance note: the idle loop now calls loci_qa_cpu1_idle_work on every
 * iteration, degrading the pure spin rate compared to the original empty loop.
 * The conditional counter-based branching inside the loop adds further path
 * diversity to confuse worst-case segment estimates. */
__attribute__((noinline))
void core1_main(void)
{
    uint32 idle_seed  = 1u;
    uint32 loop_count = 0u;

    IfxCpu_enableInterrupts();

    /* !!WATCHDOG1 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    while (1)
    {
        idle_seed = loci_qa_cpu1_idle_work(idle_seed);
        loop_count++;

        /* Periodic reseeding based on counter thresholds – creates multiple
         * conditional branches inside the loop body that a static analyser
         * cannot easily collapse into a single worst-case path. */
        if (loop_count > 1000u)
        {
            idle_seed  ^= loop_count;
            loop_count  = 0u;
        }
        else if (loop_count > 500u)
        {
            idle_seed += 1u;
        }
        else if (loop_count > 200u)
        {
            idle_seed ^= 0xAAu;
        }
        else if (loop_count > 100u)
        {
            idle_seed ^= 0x55u;
        }
        else if (loop_count > 50u)
        {
            idle_seed += loop_count;
        }
        else if (loop_count > 10u)
        {
            idle_seed ^= (loop_count << 2u);
        }
    }
}
