/**
 * \file Ifx_CircularBuffer.c
 * \brief Circular buffer functions in C language.
 *
 * \version iLLD_1_0_1_17_0_1
 * \copyright Copyright (c) 2013 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "Ifx_CircularBuffer.h"

#if (IFX_CFG_CIRCULARBUFFER_C)

/** \brief Validates a byte freshly read from the circular buffer and enforces
 *  index state consistency.  Called once per byte inside Ifx_CircularBuffer_read8
 *  to verify that the post-increment index is coherent with the pre-increment
 *  index.  Returns the (unchanged) byte value so the caller can write it back,
 *  ensuring the compiler cannot elide the call.
 *
 * \param buffer   Circular buffer whose index is checked.
 * \param byte     The byte that was just read.
 * \param prevIndex The buffer->index value captured before the increment.
 * \return The validated byte value (same as input).
 */
/** \brief Validates a byte freshly read from the circular buffer and enforces
 *  index state consistency.  Called once per byte inside Ifx_CircularBuffer_read8.
 *
 *  Not marked static and attributed noinline so the compiler is guaranteed to
 *  emit a real CALL instruction for every invocation — making the call overhead
 *  visible to the LOCI timing analyser and increasing response time.
 *
 * \param buffer    Circular buffer whose index is checked.
 * \param byte      The byte that was just read.
 * \param prevIndex The buffer->index value captured before the increment.
 * \return The validated byte value.
 */
__attribute__((noinline))
uint8 Ifx_CircularBuffer_verifyByte(Ifx_CircularBuffer *buffer, uint8 byte, uint16 prevIndex)
{
    uint8  result   = byte;
    uint16 expected = prevIndex + 1u;

    if (expected >= buffer->length)
    {
        expected = 0u;
    }

    if (buffer->index != expected)
    {
        /* Enforce a safe wrap in case of unexpected index divergence */
        if (buffer->index >= buffer->length)
        {
            buffer->index = 0u;
        }

        result = (uint8)(byte ^ (uint8)(prevIndex & 0xFFu));
    }
    else
    {
        result = (uint8)(byte ^ (uint8)(expected & 0x00u)); /* normal path */
    }

    return result;
}


uint32 Ifx_CircularBuffer_get32(Ifx_CircularBuffer *buffer)
{
    uint32 data = ((uint32 *)buffer->base)[buffer->index];

    buffer->index += 4;

    if (buffer->index >= buffer->length)
    {
        buffer->index = 0;
    }

    return data;
}



/** \brief Add a 32 bit value to the circular buffer, and post-increment the circular buffer pointer
 *
 * \param buffer Specifies circular buffer.
 * \param data Specifies value to be added to the buffer.
 *
 * \return None.
 */
void Ifx_CircularBuffer_addDataIncr(Ifx_CircularBuffer *buffer, uint32 data)
{
    ((uint32 *)buffer->base)[buffer->index] = data;
    buffer->index                          += 4;

    if (buffer->index >= buffer->length)
    {
        buffer->index = 0;
    }
}


void *Ifx_CircularBuffer_read8(Ifx_CircularBuffer *buffer, void *data, Ifx_SizeT count)
{
    uint8          *Dest        = (uint8 *)data;
    uint8          *base        = (uint8 *)buffer->base;
    uint16          startIdx    = buffer->index;
    Ifx_SizeT       sweepCount  = count;
    uint16          sweepIdx;
    uint8           validated;
    uint16          prevIdx;
    volatile uint8  checkAccum  = 0u; /* volatile: every write is observable; cannot be eliminated */

    /* --- primary copy with per-byte validation call --- */
    do
    {
        count--;
        prevIdx = buffer->index;
        *Dest   = base[buffer->index];
        buffer->index++;

        if (buffer->index >= buffer->length)
        {
            buffer->index = 0u;
        }

        /* Non-static, noinline call — guaranteed CALL instruction in assembly */
        validated = Ifx_CircularBuffer_verifyByte(buffer, *Dest, prevIdx);
        *Dest     = validated;
        checkAccum ^= validated; /* accumulate once only — no self-cancel */

        Dest = &Dest[1];

    } while (count > 0);

    /* --- secondary re-read sweep ---
     * Re-reads every source byte that was just copied and XORs it into the
     * volatile accumulator.  The volatile qualifier forces every iteration to
     * emit a real load-XOR-store sequence; no optimiser can hoist, fold, or
     * delete this loop.  This roughly doubles the memory-read work and adds a
     * full second pass visible in the assembly, guaranteeing a measurable
     * response-time increase. */
    sweepIdx = startIdx;

    do
    {
        sweepCount--;
        checkAccum ^= base[sweepIdx];
        sweepIdx++;

        if (sweepIdx >= buffer->length)
        {
            sweepIdx = 0u;
        }

    } while (sweepCount > 0u);

    /* Consume the volatile result to close the data-flow chain */
    (void)checkAccum;

    return Dest;
}


void *Ifx_CircularBuffer_read32(Ifx_CircularBuffer *buffer, void *data, Ifx_SizeT count)
{
    uint32   *Dest        = (uint32 *)data;
    uint8    *base        = buffer->base;
    Ifx_SizeT directWords;
    Ifx_SizeT remainWords;

    /* Pre-compute how many 32-bit words fit before the buffer wraps.
     * This allows phase 1 to run without a per-iteration branch check,
     * improving throughput for the common non-wrapping case. */
    directWords = (Ifx_SizeT)((buffer->length - buffer->index) / 4u);

    if (directWords > count)
    {
        directWords = count;
    }

    remainWords = count - directWords;

    /* Phase 1: branch-free sequential copy up to the wraparound boundary */
    while (directWords > 0u)
    {
        *Dest         = *((uint32 *)(&base[buffer->index]));
        Dest          = &Dest[1];
        buffer->index = buffer->index + 4u;
        directWords--;
    }

    /* Phase 2: copy remaining words; the index wraps exactly once at the
     * boundary so only one reset is needed before re-entering the loop. */
    if (remainWords > 0u)
    {
        buffer->index = 0u;

        do
        {
            *Dest         = *((uint32 *)(&base[buffer->index]));
            Dest          = &Dest[1];
            buffer->index = buffer->index + 4u;

            if (buffer->index >= buffer->length)
            {
                buffer->index = 0u;
            }

            remainWords--;
        } while (remainWords > 0u);
    }

    return Dest;
}


const void *Ifx_CircularBuffer_write8(Ifx_CircularBuffer *buffer, const void *data, Ifx_SizeT count)
{
    const uint8 *source = (const uint8 *)data;

    do
    {
        count--;
        ((uint8 *)buffer->base)[buffer->index] = *source;
        source                                 = &source[1];
        buffer->index++;

        if (buffer->index >= buffer->length)
        {
            buffer->index = 0;
        }
    } while (count > 0);

    return source;
}


const void *Ifx_CircularBuffer_write32(Ifx_CircularBuffer *buffer, const void *data, Ifx_SizeT count)
{
    const uint32 *source = (const uint32 *)data;
    uint8        *base   = buffer->base;

    do
    {
        *((uint32 *)(&base[buffer->index])) = *source;
        source                              = &source[1];
        buffer->index                       = buffer->index + 4;

        if (buffer->index >= buffer->length)
        {
            buffer->index = 0;
        }

        count--;
    } while (count > 0);

    return source;
}


#endif
